import { Esercizio, Allenamento, Squadra } from '../types';

export const DEMO_SQUADRE: Omit<Squadra, 'id' | 'coachId' | 'createdAt'>[] = [
  {
    nome: 'Under 16 Femminile',
    categoria: 'U16',
    stagione: '2026/2027',
    note: 'Gruppo competitivo regionale, focus su fase battuta-punto e transizioni veloci',
  },
  {
    nome: 'Prima Squadra Maschile',
    categoria: 'Serie C',
    stagione: '2026/2027',
    note: 'Focus su efficienza cambio palla e correlazione muro-difesa',
  },
  {
    nome: 'Under 14 Mista',
    categoria: 'U14',
    stagione: '2026/2027',
    note: 'Focus su tecnica analitica e giochi propedeutici',
  },
];

export const DEMO_ESERCIZI: Omit<Esercizio, 'id' | 'coachId' | 'createdAt'>[] = [
  {
    titolo: 'Riscaldamento con palla e attivazione',
    categoria: 'Riscaldamento',
    durata: 15,
    difficolta: 'Base',
    obiettivo: 'Attivazione dinamica, controllo del tocco e propriocezione in coppia',
    minPlayers: 6,
    maxPlayers: 14,
    materiale: '1 pallone ogni due atleti, linee del campo',
    descrizione:
      'I giocatori lavorano a coppie lungo le linee perimetrali. Sequenza: 10 bagher di controllo + 10 palleggi + attacco piazzato controllato con difesa a terra. Incrementare progressivamente intensità e distanza.',
    note: 'Controllare la postura del piano di rimbalzo nel bagher e la spinta delle gambe nel palleggio.',
    isFavorite: true,
    isDemo: true,
    boardData: JSON.stringify({
      version: 1,
      items: [
        { id: 'p1', type: 'player', x: 200, y: 150, label: '1', color: '#2563eb' },
        { id: 'p2', type: 'player', x: 200, y: 350, label: '2', color: '#2563eb' },
        { id: 'b1', type: 'ball', x: 200, y: 250 },
        { id: 'a1', type: 'dashed_line', x: 200, y: 175, endX: 200, endY: 325, color: '#facc15' },
        { id: 'p3', type: 'player', x: 350, y: 150, label: '3', color: '#2563eb' },
        { id: 'p4', type: 'player', x: 350, y: 350, label: '4', color: '#2563eb' },
        { id: 'b2', type: 'ball', x: 350, y: 250 },
        { id: 'a2', type: 'dashed_line', x: 350, y: 175, endX: 350, endY: 325, color: '#facc15' },
      ],
    }),
  },
  {
    titolo: 'Ricezione a coppie con spostamento laterale',
    categoria: 'Ricezione',
    durata: 20,
    difficolta: 'Intermedio',
    obiettivo: 'Lettura della traiettoria corta/lunga e stabilità del piano di rimbalzo',
    minPlayers: 4,
    maxPlayers: 12,
    materiale: 'Palloni da gara, coni segnalatori per delimitare i corridoi',
    descrizione:
      'Il battitore esegue una battuta fluttuante mirata verso la zona 5 o 6. I due ricettori comunicano chiamando la palla, compiono un passo di aggiustamento laterale e indirizzano la ricezione precisa verso la zona 2/3 (alzatore target).',
    note: 'Chiedere ai ricettori di fermare i piedi prima del contatto con la palla per garantire massima precisione.',
    isFavorite: true,
    isDemo: true,
    boardData: JSON.stringify({
      version: 1,
      items: [
        { id: 'coach1', type: 'coach', x: 150, y: 250, label: 'ALL', color: '#facc15' },
        { id: 'b1', type: 'ball', x: 180, y: 250 },
        { id: 'c1', type: 'cone', x: 600, y: 150 },
        { id: 'c2', type: 'cone', x: 600, y: 350 },
        { id: 'p1', type: 'player', x: 650, y: 180, label: '5', color: '#16a34a' },
        { id: 'p2', type: 'player', x: 650, y: 320, label: '6', color: '#16a34a' },
        { id: 'target', type: 'player', x: 500, y: 150, label: 'P', color: '#9333ea' },
        { id: 'arr1', type: 'dashed_line', x: 200, y: 250, endX: 630, endY: 200, color: '#fbbf24' },
        { id: 'arr2', type: 'arrow', x: 640, y: 190, endX: 515, endY: 155, color: '#ffffff' },
      ],
    }),
  },
  {
    titolo: 'Difesa e contrattacco in transizione rapida',
    categoria: 'Difesa',
    durata: 25,
    difficolta: 'Avanzato',
    obiettivo: 'Velocità di apertura dell attaccante dopo una difesa impegnativa',
    minPlayers: 6,
    maxPlayers: 12,
    materiale: 'Palloni, plinti di battuta per alzare la traiettoria di attacco',
    descrizione:
      'L allenatore attacca da sopra un plinto verso la zona 5 o 1. Il difensore recupera la palla verso il centro del campo. L alzatore alza in banda o al centro in primo tempo, con l attaccante che apre tempestivamente la rincorsa e chiude il punto.',
    note: 'Focalizzarsi sul tempo di stacco dell attaccante che non deve partire prima della valutazione della difesa.',
    isFavorite: true,
    isDemo: true,
    boardData: JSON.stringify({
      version: 1,
      items: [
        { id: 'plinto', type: 'plinth', x: 420, y: 150 },
        { id: 'coach', type: 'coach', x: 420, y: 150, label: 'ALL' },
        { id: 'def1', type: 'player', x: 720, y: 160, label: '5', color: '#dc2626' },
        { id: 'def2', type: 'player', x: 720, y: 340, label: '1', color: '#dc2626' },
        { id: 'set', type: 'player', x: 500, y: 200, label: '4', color: '#2563eb' },
        { id: 'att', type: 'player', x: 720, y: 250, label: '9', color: '#2563eb' },
        { id: 'arrCurve', type: 'curved_arrow', x: 700, y: 250, endX: 490, endY: 340, controlX: 620, controlY: 360, color: '#38bdf8' },
      ],
    }),
  },
  {
    titolo: 'Battuta tattica e ricezione sotto pressione',
    categoria: 'Battuta e ricezione',
    durata: 20,
    difficolta: 'Intermedio',
    obiettivo: 'Precisione di battuta nelle zone di conflitto tra ricettori (1-6 e 5-6)',
    minPlayers: 8,
    maxPlayers: 14,
    materiale: 'Ceste di palloni, bersagli a terra (tappetini)',
    descrizione:
      'I battitori hanno come obiettivo colpire le zone di conflitto assegnate dall allenatore. La linea di ricezione (3 atleti) guadagna punti se porta la ricezione nel metro quadro ideale (#), la battuta guadagna punti su ace o ricezione staccata.',
    note: 'Incentivare il battitore ad aggredire con velocità di braccio senza timore di sbagliare.',
    isFavorite: false,
    isDemo: true,
    boardData: JSON.stringify({
      version: 1,
      items: [
        { id: 'srv1', type: 'player', x: 80, y: 250, label: '7', color: '#2563eb' },
        { id: 'ball', type: 'ball', x: 95, y: 250 },
        { id: 'r1', type: 'player', x: 680, y: 150, label: '5', color: '#16a34a' },
        { id: 'r2', type: 'player', x: 740, y: 250, label: '6', color: '#16a34a' },
        { id: 'r3', type: 'player', x: 680, y: 350, label: '1', color: '#16a34a' },
        { id: 'traj', type: 'dashed_line', x: 100, y: 250, endX: 710, endY: 200, color: '#facc15' },
      ],
    }),
  },
  {
    titolo: 'Attacco di posto 4 contro muro a due composto',
    categoria: 'Attacco e difesa',
    durata: 20,
    difficolta: 'Avanzato',
    obiettivo: 'Scelta del colpo d attacco (mani-fuori, diagonale stretta, pallonetto dietro il muro)',
    minPlayers: 8,
    maxPlayers: 14,
    materiale: 'Palloni da gara, aste di delimitazione',
    descrizione:
      'L alzatore riceve palla perfetta e smista in posto 4. Sul lato opposto il centrale e l opposto compongono un muro a due compatto. L attaccante deve leggere la posizione delle mani a muro e variare il colpo.',
    note: 'Il muro deve invadere senza toccare la rete, chiudendo l angolo preferenziale.',
    isFavorite: false,
    isDemo: true,
    boardData: JSON.stringify({
      version: 1,
      items: [
        { id: 's1', type: 'player', x: 380, y: 150, label: 'P', color: '#2563eb' },
        { id: 'spk', type: 'player', x: 260, y: 120, label: '4', color: '#2563eb' },
        { id: 'm1', type: 'player', x: 470, y: 110, label: '2', color: '#dc2626' },
        { id: 'm2', type: 'player', x: 470, y: 140, label: '3', color: '#dc2626' },
        { id: 'run', type: 'arrow', x: 230, y: 110, endX: 380, endY: 110, color: '#ffffff' },
      ],
    }),
  },
  {
    titolo: 'Gioco 6 contro 6 con palla di bonus su punto break',
    categoria: 'Globale',
    durata: 30,
    difficolta: 'Intermedio',
    obiettivo: 'Gestione del punteggio in situazione di parità e concentrazione sulla palla break',
    minPlayers: 12,
    maxPlayers: 16,
    materiale: 'Segnapunti, palloni da gara, fischietto',
    descrizione:
      'Partita a rotazioni regolari. Ogni rotazione parte da punteggio 20-20. La squadra al servizio che realizza un break point riceve immediatamente una free ball di bonus per raddoppiare il vantaggio.',
    note: 'Simulare la pressione psicologica del finale di set.',
    isFavorite: true,
    isDemo: true,
    boardData: JSON.stringify({
      version: 1,
      items: [
        // Team A (left)
        { id: 'a4', type: 'player', x: 360, y: 150, label: '4', color: '#2563eb' },
        { id: 'a3', type: 'player', x: 360, y: 250, label: '3', color: '#2563eb' },
        { id: 'a2', type: 'player', x: 360, y: 350, label: '2', color: '#2563eb' },
        { id: 'a5', type: 'player', x: 200, y: 150, label: '5', color: '#2563eb' },
        { id: 'a6', type: 'player', x: 180, y: 250, label: '6', color: '#2563eb' },
        { id: 'a1', type: 'player', x: 200, y: 350, label: '1', color: '#2563eb' },
        // Team B (right)
        { id: 'b2', type: 'player', x: 540, y: 150, label: '2', color: '#dc2626' },
        { id: 'b3', type: 'player', x: 540, y: 250, label: '3', color: '#dc2626' },
        { id: 'b4', type: 'player', x: 540, y: 350, label: '4', color: '#dc2626' },
        { id: 'b1', type: 'player', x: 700, y: 150, label: '1', color: '#dc2626' },
        { id: 'b6', type: 'player', x: 720, y: 250, label: '6', color: '#dc2626' },
        { id: 'b5', type: 'player', x: 700, y: 350, label: '5', color: '#dc2626' },
        { id: 'ball', type: 'ball', x: 450, y: 250 },
      ],
    }),
  },
];
